CREATE TABLE KOBO_PRODUCT_MAPPING (
    BOOK_ID varchar NOT NULL PRIMARY KEY,
    ISBN varchar NOT NULL,
    PRODUCT_ID varchar,
    STATUS varchar NOT NULL,
    CHECKED_AT datetime NOT NULL,

    FOREIGN KEY (BOOK_ID)
        REFERENCES BOOK(ID)
        ON DELETE CASCADE,

    CHECK (STATUS IN ('FOUND', 'NOT_FOUND')),

    CHECK (
        (STATUS = 'FOUND' AND PRODUCT_ID IS NOT NULL)
        OR
        (STATUS = 'NOT_FOUND' AND PRODUCT_ID IS NULL)
    )
);

CREATE INDEX IDX_KOBO_PRODUCT_MAPPING_ISBN
    ON KOBO_PRODUCT_MAPPING(ISBN);

CREATE INDEX IDX_KOBO_PRODUCT_MAPPING_PRODUCT_ID
    ON KOBO_PRODUCT_MAPPING(PRODUCT_ID);