CREATE TABLE KOBO_KEPUB_SIZE_CACHE_NEW (
    BOOK_ID TEXT NOT NULL PRIMARY KEY,
    SOURCE_FILE_HASH TEXT NOT NULL,
    KEPUB_FILE_SIZE INTEGER NOT NULL,

    FOREIGN KEY (BOOK_ID)
        REFERENCES BOOK(ID)
        ON DELETE CASCADE
);

DROP TABLE KOBO_KEPUB_SIZE_CACHE;

ALTER TABLE KOBO_KEPUB_SIZE_CACHE_NEW
    RENAME TO KOBO_KEPUB_SIZE_CACHE;
