CREATE TABLE KOBO_EXTERNAL_COLLECTION_MEMBER (
    USER_ID varchar NOT NULL,
    READLIST_ID varchar NOT NULL,
    REVISION_ID varchar NOT NULL,
    PRIMARY KEY (USER_ID, READLIST_ID, REVISION_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE CASCADE,
    FOREIGN KEY (READLIST_ID) REFERENCES READLIST(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_KOBO_EXTERNAL_COLLECTION_MEMBER_READLIST
    ON KOBO_EXTERNAL_COLLECTION_MEMBER(READLIST_ID);
