-- KOBO_PERSISTENT_SERIES_MAPPING_V2
CREATE TABLE KOBO_SERIES_MAPPING (
    SERIES_ID TEXT NOT NULL PRIMARY KEY,
    KOBO_SERIES_ID TEXT NOT NULL,

    FOREIGN KEY (SERIES_ID)
        REFERENCES SERIES(ID)
        ON DELETE CASCADE
);

CREATE INDEX KOBO_SERIES_MAPPING_KOBO_ID_IDX
    ON KOBO_SERIES_MAPPING(KOBO_SERIES_ID);
