CREATE TABLE KOBO_ARCHIVED_BOOK (
    USER_ID TEXT NOT NULL,
    BOOK_ID TEXT NOT NULL,
    ARCHIVED_AT TEXT NOT NULL,

    PRIMARY KEY (USER_ID, BOOK_ID),

    FOREIGN KEY (BOOK_ID)
        REFERENCES BOOK(ID)
        ON DELETE CASCADE
);

CREATE INDEX IDX_KOBO_ARCHIVED_BOOK_USER_ID
    ON KOBO_ARCHIVED_BOOK(USER_ID);
