CREATE TABLE KOBO_ARCHIVED_BOOK_NEW (
    USER_ID TEXT NOT NULL,
    BOOK_ID TEXT NOT NULL,
    ARCHIVED_AT TEXT NOT NULL,

    PRIMARY KEY (USER_ID, BOOK_ID),

    FOREIGN KEY (USER_ID)
        REFERENCES USER(ID)
        ON DELETE CASCADE,

    FOREIGN KEY (BOOK_ID)
        REFERENCES BOOK(ID)
        ON DELETE CASCADE
);

INSERT INTO KOBO_ARCHIVED_BOOK_NEW (USER_ID, BOOK_ID, ARCHIVED_AT)
SELECT archived.USER_ID, archived.BOOK_ID, archived.ARCHIVED_AT
FROM KOBO_ARCHIVED_BOOK archived
JOIN USER u ON u.ID = archived.USER_ID
JOIN BOOK b ON b.ID = archived.BOOK_ID;

DROP TABLE KOBO_ARCHIVED_BOOK;

ALTER TABLE KOBO_ARCHIVED_BOOK_NEW
    RENAME TO KOBO_ARCHIVED_BOOK;

CREATE INDEX IDX_KOBO_ARCHIVED_BOOK_USER_ID
    ON KOBO_ARCHIVED_BOOK(USER_ID);
