-- Snapshot a user's archived books alongside Komga's existing paginated book sync state.
ALTER TABLE SYNC_POINT_BOOK
    ADD COLUMN KOBO_ARCHIVED BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE SYNC_POINT_BOOK
    ADD COLUMN KOBO_ARCHIVE_SYNCED BOOLEAN NOT NULL DEFAULT FALSE;
